export type Lang = "en" | "es" | "ru";

export const content = {
  en: {
    label: "English",
    nav: {
      method: "How it works",
      curriculum: "Course",
      skills: "Skills",
      pricing: "Price",
      cta: "Get access",
    },
    hero: {
      pill: "500+ graduates · 2–4 weeks",
      title: ["Four weeks from now,", "you'll hand AI the work ", "you do by hand today", "."],
      sub: "Not a video course. A lesson, homework on your own real work, and a real teacher who checks it. You finish with ready-made setups that write your reports and emails for you.",
      cta: "Get access",
      ghost: "How it works",
      was: "$299",
      now: "$150",
      tags: ["ChatGPT", "Claude", "Gemini", "No coding"],
      gloss: "Prompta aut perire is Latin for \"prompt, or perish\". A prompt is simply the text you write to explain what you need.",
      app: {
        heading: "setup 09",
        week: "lesson 02",
        outLabel: "the answer",
        result: [
          "Margin up 4% — two large deals behind it",
          "Risk: one client is 40% of revenue (p. 12)",
          "Decision: renew the contractor or not",
        ],
        stack: ["setup 07", "setup 08"],
      },
    },
    pain: {
      eyebrow: "Sound familiar?",
      title: "You know AI could do this. You still do it by hand.",
      items: [
        {
          q: "You've watched the videos and still don't know what to type.",
          a: "Videos show you buttons. Nobody shows you how to take your own task all the way to done.",
        },
        {
          q: "The answer comes back smooth and useless. You rewrite it yourself.",
          a: "It's not the AI. It's how you asked. That takes a couple of hours to learn.",
        },
        {
          q: "Every Monday it's the same report, the same summary.",
          a: "You can hand that over once and never do it by hand again.",
        },
        {
          q: "A colleague does in an hour what takes you a day.",
          a: "They're not smarter. They have setups. You'll build yours in four weeks.",
        },
      ],
    },
    mechanism: {
      eyebrow: "The difference",
      title: "You build setups. One per lesson.",
      lede: "Tricks fade. A setup doesn't. You describe the job once, then just run it again — every Monday, for every client.",
      pillars: [
        {
          n: "You build",
          title: "A setup for your own job",
          text: "Your real report, your real email, your real contract. Not a practice exercise.",
        },
        {
          n: "We check",
          title: "A teacher finds the mistakes",
          text: "They read what you built and show where it will let you down. Video can't do that.",
        },
        {
          n: "You keep it",
          title: "The setup is yours for good",
          text: "A month in you have a whole set. They work even after you've forgotten how you made them.",
        },
      ],
      example: {
        label: "Here's what one looks like",
        name: "Weekly report for my director",
        lines: [
          "You're writing a report for my director. She reads for 90 seconds.",
          "I'll paste this week's figures. Give me: what changed and why,",
          "one risk, and one decision waiting on her.",
          "One page, no adjectives.",
        ],
        note: "That's it. Ordinary text, written in plain words and saved once. Every Monday you open it, paste in the week's figures, and get a finished report. By the end of the course you have nine of these, built around the work you repeat.",
      },
      close: "That's why graduates are still using theirs six months later.",
    },
    scene: {
      eyebrow: "Four weeks, watched from above",
      title: "One setup per lesson. Nine by the end.",
      note: "Keep scrolling and watch them land. Each one is a job you used to do by hand, described once and kept for good.",
      counter: "setups built",
    },
    demo: {
      eyebrow: "See it",
      title: "The difference is in how you ask",
      lede: "Same AI, same task. Both sides are ordinary text, typed into the chat in plain words. Pick whichever is closest to your week.",
      badLabel: "What most people write",
      goodLabel: "What you'll write",
      resultLabel: "The answer",
      note: "No secret words. Just a clear brief: who's reading, what matters, what shape the answer takes.",
      tabs: [
        {
          id: "report",
          label: "A report for your boss",
          bad: {
            prompt: "Summarise this report for my director.",
            result: "Eight paragraphs of retelling. No figures, no conclusions. You rewrite it yourself.",
          },
          good: {
            prompt: [
              "A brief for my director. She reads for 90 seconds and asks about money first.",
              "Give me three figures that moved, and why.",
              "Two risks, each with the page it's on.",
              "One decision that's waiting on her.",
              "One page.",
            ],
            result: "A page that opens with the money. Every figure tied to a page number. Sent as it is.",
          },
        },
        {
          id: "client",
          label: "Bad news for a client",
          bad: {
            prompt: "Write to the client that the deadline is slipping two weeks.",
            result: "A polite apology with no plan. The client calls your manager.",
          },
          good: {
            prompt: [
              "Client expected the 14th, it'll be the 28th. Cause: our supplier let us down.",
              "First line: the new date and what they get this week anyway.",
              "Then the cause in one sentence, no excuses.",
              "End with what I need from them and by when.",
              "Eight lines, calm tone.",
            ],
            result: "An email that opens with the fix, not the apology. They reply with an answer.",
          },
        },
        {
          id: "contract",
          label: "Checking a contract",
          bad: {
            prompt: "Read this contract and tell me what's wrong.",
            result: "A retelling of the clauses and \"see a lawyer\". You read it yourself anyway.",
          },
          good: {
            prompt: [
              "I'm the supplier. $12,000, three months.",
              "Find clauses that could make me work or pay beyond the deal.",
              "Find where they can walk away without paying.",
              "For each: the quote, the clause number, and what to propose instead.",
              "Skip the clauses that are fine.",
            ],
            result: "Six clauses with quotes and numbers, each with replacement wording. Twenty minutes, not an evening.",
          },
        },
      ],
    },
    method: {
      eyebrow: "How the course runs",
      title: "You're taught, not handed a login",
      lede: "Most courses give you a folder of videos. Nobody finishes those. Here the next lesson won't open until the last one is done.",
      steps: [
        { n: "01", title: "Lesson", text: "Short, practical, built around one task." },
        { n: "02", title: "Check", text: "Didn't understand it? You don't move on." },
        { n: "03", title: "Homework", text: "On your own real work, not a made-up example." },
        { n: "04", title: "Review", text: "A real person reads what you did and corrects it." },
      ],
      platform: "It all runs on our own platform: lessons, homework, corrections, progress. On a laptop or a phone, in the hours you actually have.",
      note: "If you want a folder of videos, this isn't it. Here you'll have to work.",
    },
    curriculum: {
      eyebrow: "The course",
      title: "Six modules. After each one, something works.",
      sub: "",
      modules: [
        {
          n: "01",
          title: "How this works",
          text: "What these systems can do, how they differ, and where they lie with total confidence.",
          result: "You know what to trust and what to check.",
        },
        {
          n: "02",
          title: "How to ask",
          text: "What a request that works first time is actually made of.",
          result: "You send the answer as it is.",
        },
        {
          n: "03",
          title: "Documents and spreadsheets",
          text: "Contracts, reports, invoices, scans and photos of paperwork.",
          result: "Sixty pages become one.",
        },
        {
          n: "04",
          title: "Your own helper",
          text: "It remembers your clients and your style. Plus voice input.",
          result: "You stop explaining everything again each morning.",
        },
        {
          n: "05",
          title: "Routine without you",
          text: "Reports, summaries, meeting write-ups, finding information.",
          result: "Monday: ten minutes instead of a morning.",
        },
        {
          n: "06",
          title: "Your own tools",
          text: "A small program for your own job, without a line of code.",
          result: "One evening, instead of a quarter waiting on IT.",
        },
      ],
    },
    outcomes: {
      eyebrow: "Skills",
      title: "Nine things you'll be able to do",
      sub: "Find yours — the one that costs you an evening every week.",
      skills: [
        { title: "Tell fact from invention", text: "AI invents figures with total confidence. You'll catch it before you send anything." },
        { title: "Get it right first time", text: "The same request, asked properly. Nothing left to rewrite." },
        { title: "Get through documents", text: "Contract, report, invoice, scan: what matters, where the catch is, what's missing." },
        { title: "Have a helper that knows you", text: "It remembers your clients and does it your way from the start." },
        { title: "Work by voice", text: "Dictate on the way in, get back a finished email or task list." },
        { title: "Hand over the routine", text: "Reports, summaries and meeting notes get done without you." },
        { title: "Test ideas risk-free", text: "Invented customers tear your copy or your price apart first." },
        { title: "Build your own tools", text: "A calculator, a bot, a small program — in an evening, without coding." },
        { title: "Take your team with you", text: "Roll the same thing out to your department and show the numbers." },
      ],
      stats: [
        { v: "500+", l: "Graduates" },
        { v: "2–4", l: "Weeks" },
        { v: "100%", l: "Homework checked" },
        { v: "0", l: "Lines of code" },
      ],
    },
    testimonials: {
      eyebrow: "Graduates",
      title: "What people say afterwards",
      items: [] as { quote: string; name: string; role: string; result: string }[],
    },
    cost: {
      eyebrow: "Honestly",
      title: "Put it off and nothing bad happens. That's the problem.",
      text: "The loss never arrives as a bill. It arrives as lost evenings and a colleague who quietly got faster than you. Two hours a week is thirteen working days a year. This costs less than one of them.",
      cta: "Start this week",
    },
    faq: {
      eyebrow: "Questions",
      title: "What people ask most",
      items: [
        {
          q: "What if I can't do it?",
          a: "A person checks your homework — if it isn't working, they show you exactly where and you redo it. And the course is short: if a week in you decide it isn't for you, you've lost a week, not half a year.",
        },
        {
          q: "This is all free on YouTube.",
          a: "It is — in pieces, in no order, with nobody to tell you what you got wrong. You're paying for the order, for homework on your own work, and for the review. If you have 200 spare hours, YouTube genuinely works.",
        },
        {
          q: "I'm not technical at all.",
          a: "There's no programming anywhere in it. If you can use a browser, you'll keep up. The only people who struggle are the ones who skip the homework.",
        },
        {
          q: "I don't have time.",
          a: "Lessons are short and the whole thing runs 2–4 weeks at your pace. It costs you less time than the tasks it removes.",
        },
        {
          q: "Do I need a paid subscription?",
          a: "You can start free. Where a paid plan helps, we tell you first — before you spend anything.",
        },
        {
          q: "I already use ChatGPT daily.",
          a: "Daily users usually get the most: they arrive with real tasks and see how much they still do by hand.",
        },
        {
          q: "What happens after I apply?",
          a: "A person emails you with start dates and how to join. No funnels, no cold calls.",
        },
      ],
    },
    pricing: {
      eyebrow: "Price",
      title: "One course. One price.",
      sub: "No tiers, no upsells. Everyone gets everything, review included.",
      was: "$299",
      now: "$150",
      includes: [
        "Six modules on the platform",
        "A check after every lesson",
        "Homework on your own real tasks",
        "Review and correction by a person",
        "Your setups — yours to keep",
      ],
      cta: "Request access",
    },
    form: {
      title: "Request access",
      sub: "Name and email. A person replies, usually the same day.",
      name: "Name",
      namePh: "Maria Gonzalez",
      email: "Email",
      emailPh: "you@company.com",
      submit: "Send",
      sending: "Sending…",
      success: "Thank you! We'll be in touch.",
      successSub: "A person will email you about the next steps.",
      errName: "Please enter your name.",
      errEmail: "Please enter a valid email.",
      errSend: "Something went wrong. Please try again.",
      privacy: "We only use this to contact you. No mailing lists.",
    },
    footer: {
      tagline: "Prompt, or perish.",
      rights: "All rights reserved.",
    },
  },
  es: {
    label: "Español",
    nav: {
      method: "Cómo funciona",
      curriculum: "Curso",
      skills: "Habilidades",
      pricing: "Precio",
      cta: "Obtener acceso",
    },
    hero: {
      pill: "Más de 500 graduados · 2–4 semanas",
      title: ["Dentro de cuatro semanas", "le pasarás a la IA ", "lo que hoy haces a mano", "."],
      sub: "No es un curso en vídeo. Una lección, una tarea sobre tu trabajo real y un profesor de verdad que la corrige. Terminas con montajes listos que escriben tus informes y tus correos.",
      cta: "Obtener acceso",
      ghost: "Cómo funciona",
      was: "$299",
      now: "$150",
      tags: ["ChatGPT", "Claude", "Gemini", "Sin programar"],
      gloss: "Prompta aut perire es latín: «promptea o perece». Un prompt es simplemente el texto con el que explicas lo que necesitas.",
      app: {
        heading: "plantilla 09",
        week: "lección 02",
        outLabel: "la respuesta",
        result: [
          "El margen sube un 4% — por dos grandes ventas",
          "Riesgo: un cliente es el 40% de los ingresos (p. 12)",
          "Decisión: renovar al proveedor o no",
        ],
        stack: ["plantilla 07", "plantilla 08"],
      },
    },
    pain: {
      eyebrow: "¿Te suena?",
      title: "Sabes que la IA podría hacerlo. Y sigues haciéndolo a mano.",
      items: [
        {
          q: "Has visto los vídeos y sigues sin saber qué escribir.",
          a: "Los vídeos enseñan botones. Nadie te enseña a llevar tu tarea hasta el final.",
        },
        {
          q: "La respuesta vuelve pulida e inútil. La reescribes tú.",
          a: "No es la IA, es cómo lo pediste. Eso se aprende en un par de horas.",
        },
        {
          q: "Cada lunes, el mismo informe y el mismo resumen.",
          a: "Eso se delega una vez y no se vuelve a hacer a mano nunca.",
        },
        {
          q: "Un compañero hace en una hora lo que a ti te lleva un día.",
          a: "No es más listo. Tiene montajes. Los tuyos los harás en cuatro semanas.",
        },
      ],
    },
    mechanism: {
      eyebrow: "La diferencia",
      title: "Montas plantillas. Una por lección.",
      lede: "Los trucos se olvidan. Una plantilla no. Describes el trabajo una vez y después solo la vuelves a lanzar: cada lunes, para cada cliente.",
      pillars: [
        {
          n: "La montas",
          title: "Una plantilla para tu trabajo",
          text: "Tu informe real, tu correo real, tu contrato real. No un ejercicio.",
        },
        {
          n: "La revisan",
          title: "El profesor encuentra los fallos",
          text: "Lee lo que montaste y te enseña dónde te va a fallar. El vídeo no hace eso.",
        },
        {
          n: "Te la quedas",
          title: "La plantilla es tuya para siempre",
          text: "Al mes tienes un conjunto. Funcionan aunque hayas olvidado cómo las hiciste.",
        },
      ],
      example: {
        label: "Así es una de ellas",
        name: "Informe semanal para mi directora",
        lines: [
          "Preparas un informe para mi directora. Lee 90 segundos.",
          "Te paso las cifras de la semana. Dame: qué cambió y por qué,",
          "un riesgo y una decisión que depende de ella.",
          "Una página, sin adjetivos.",
        ],
        note: "Eso es todo. Texto normal, escrito con palabras y guardado una vez. Cada lunes lo abres, pegas las cifras de la semana y recibes el informe terminado. Al acabar el curso tienes nueve, hechas a la medida de lo que repites.",
      },
      close: "Por eso nuestros graduados siguen usándolas seis meses después.",
    },
    scene: {
      eyebrow: "Cuatro semanas, vistas desde arriba",
      title: "Una plantilla por lección. Nueve al terminar.",
      note: "Sigue bajando y míralas caer. Cada una es un trabajo que hacías a mano, descrito una vez y guardado para siempre.",
      counter: "plantillas montadas",
    },
    demo: {
      eyebrow: "Míralo",
      title: "La diferencia está en cómo lo pides",
      lede: "La misma IA, la misma tarea. A los dos lados hay texto normal, escrito con palabras en el chat. Elige lo que más se parezca a tu semana.",
      badLabel: "Lo que escribe casi todo el mundo",
      goodLabel: "Lo que escribirás tú",
      resultLabel: "La respuesta",
      note: "Sin palabras mágicas. Solo un encargo claro: quién lo lee, qué importa y qué forma tiene la respuesta.",
      tabs: [
        {
          id: "report",
          label: "Un informe para tu jefa",
          bad: {
            prompt: "Resume este informe para mi directora.",
            result: "Ocho párrafos que repiten el informe. Sin cifras ni conclusiones. Lo reescribes tú.",
          },
          good: {
            prompt: [
              "Una nota para mi directora. Lee 90 segundos y pregunta primero por el dinero.",
              "Dame tres cifras que se movieron, y por qué.",
              "Dos riesgos, cada uno con su página.",
              "Una decisión que depende de ella.",
              "Una página.",
            ],
            result: "Una página que abre con el dinero. Cada cifra con su página. Se envía tal cual.",
          },
        },
        {
          id: "client",
          label: "Malas noticias a un cliente",
          bad: {
            prompt: "Escribe al cliente que la entrega se retrasa dos semanas.",
            result: "Una disculpa educada sin plan. El cliente llama a tu responsable.",
          },
          good: {
            prompt: [
              "El cliente esperaba el 14, será el 28. Causa: falló el proveedor.",
              "Primera línea: la nueva fecha y lo que recibe esta semana igualmente.",
              "Después la causa en una frase, sin excusas.",
              "Termina con lo que necesito de él y para cuándo.",
              "Ocho líneas, tono sereno.",
            ],
            result: "Un correo que abre con la solución, no con la disculpa. Responde con una respuesta.",
          },
        },
        {
          id: "contract",
          label: "Revisar un contrato",
          bad: {
            prompt: "Lee este contrato y dime qué está mal.",
            result: "Un repaso de las cláusulas y «consulta a un abogado». Acabas leyéndolo tú.",
          },
          good: {
            prompt: [
              "Soy el proveedor. 12.000 $, tres meses.",
              "Busca cláusulas que puedan hacerme trabajar o pagar de más.",
              "Busca dónde pueden irse sin pagar.",
              "De cada una: la cita, el número y qué proponer a cambio.",
              "Las cláusulas que están bien, ni las menciones.",
            ],
            result: "Seis cláusulas con citas y números, cada una con su redacción alternativa. Veinte minutos, no una tarde.",
          },
        },
      ],
    },
    method: {
      eyebrow: "Cómo es el curso",
      title: "Te enseñan, no te dan una clave",
      lede: "La mayoría de los cursos te dan una carpeta de vídeos. Nadie los termina. Aquí la siguiente lección no se abre hasta que la anterior está hecha.",
      steps: [
        { n: "01", title: "Lección", text: "Corta, práctica, sobre una sola tarea." },
        { n: "02", title: "Control", text: "Si no lo entendiste, no avanzas." },
        { n: "03", title: "Tarea", text: "Sobre tu trabajo real, no sobre un ejemplo inventado." },
        { n: "04", title: "Corrección", text: "Una persona lee lo que hiciste y lo corrige." },
      ],
      platform: "Todo ocurre en nuestra plataforma: lecciones, tareas, correcciones y progreso. En el ordenador o en el móvil, en las horas que tengas.",
      note: "Si buscas una carpeta de vídeos, no es esto. Aquí hay que trabajar.",
    },
    curriculum: {
      eyebrow: "El curso",
      title: "Seis módulos. Tras cada uno, algo funciona.",
      sub: "",
      modules: [
        {
          n: "01",
          title: "Cómo funciona esto",
          text: "Qué saben hacer estos sistemas, en qué se diferencian y dónde mienten con total seguridad.",
          result: "Sabes de qué fiarte y qué comprobar.",
        },
        {
          n: "02",
          title: "Cómo pedirlo",
          text: "De qué se compone una petición que funciona a la primera.",
          result: "Envías la respuesta tal cual.",
        },
        {
          n: "03",
          title: "Documentos y hojas de cálculo",
          text: "Contratos, informes, facturas, escaneos y fotos de papeles.",
          result: "Sesenta páginas se convierten en una.",
        },
        {
          n: "04",
          title: "Tu propio ayudante",
          text: "Recuerda a tus clientes y tu estilo. Además, dictado por voz.",
          result: "Dejas de explicarlo todo otra vez cada mañana.",
        },
        {
          n: "05",
          title: "La rutina sin ti",
          text: "Informes, resúmenes, actas de reuniones, búsqueda de información.",
          result: "El lunes: diez minutos en vez de una mañana.",
        },
        {
          n: "06",
          title: "Tus propias herramientas",
          text: "Un programa pequeño para tu trabajo, sin una línea de código.",
          result: "Una tarde, en vez de un trimestre esperando a informática.",
        },
      ],
    },
    outcomes: {
      eyebrow: "Habilidades",
      title: "Nueve cosas que sabrás hacer",
      sub: "Busca la tuya: esa que te cuesta una tarde cada semana.",
      skills: [
        { title: "Distinguir el dato del invento", text: "La IA se inventa cifras con seguridad. Lo pillarás antes de enviar nada." },
        { title: "Acertar a la primera", text: "La misma petición, pedida como toca. Nada que reescribir." },
        { title: "Con cualquier documento", text: "Contrato, informe, factura, escaneo: qué importa, dónde está la trampa, qué falta." },
        { title: "Un ayudante que te conoce", text: "Recuerda a tus clientes y lo hace a tu manera desde el principio." },
        { title: "Trabajar con la voz", text: "Lo dictas de camino y recibes un correo o una lista de tareas terminada." },
        { title: "Soltar la rutina", text: "Informes, resúmenes y actas se hacen sin ti." },
        { title: "Probar ideas sin riesgo", text: "Clientes inventados destrozan tu texto o tu precio primero." },
        { title: "Montarte herramientas", text: "Una calculadora, un bot, un programita: en una tarde, sin programar." },
        { title: "Llevarte a tu equipo", text: "Pones lo mismo en tu departamento y enseñas las cifras." },
      ],
      stats: [
        { v: "500+", l: "Graduados" },
        { v: "2–4", l: "Semanas" },
        { v: "100%", l: "Tareas corregidas" },
        { v: "0", l: "Líneas de código" },
      ],
    },
    testimonials: {
      eyebrow: "Graduados",
      title: "Lo que dicen después",
      items: [] as { quote: string; name: string; role: string; result: string }[],
    },
    cost: {
      eyebrow: "Con franqueza",
      title: "Si lo dejas para luego no pasa nada. Ese es el problema.",
      text: "La pérdida nunca llega como una factura. Llega como tardes perdidas y un compañero que se volvió más rápido que tú. Dos horas por semana son trece días laborables al año. Esto cuesta menos que uno de ellos.",
      cta: "Empezar esta semana",
    },
    faq: {
      eyebrow: "Preguntas",
      title: "Lo que más se pregunta",
      items: [
        {
          q: "¿Y si no me sale?",
          a: "Una persona corrige tus tareas: si algo no funciona, te enseña dónde exactamente y lo rehaces. Y el curso es corto: si a la semana ves que no es lo tuyo, habrás perdido una semana, no medio año.",
        },
        {
          q: "Esto está gratis en YouTube.",
          a: "Lo está, a trozos, sin orden y sin nadie que te diga en qué te equivocaste. Pagas por el orden, por hacer las tareas sobre tu trabajo y por la corrección. Si tienes 200 horas libres, YouTube funciona de verdad.",
        },
        {
          q: "No tengo perfil técnico.",
          a: "No hay programación en ninguna parte. Si sabes usar un navegador, lo sigues. Solo sufren quienes no hacen las tareas.",
        },
        {
          q: "No tengo tiempo.",
          a: "Las lecciones son cortas y todo dura de 2 a 4 semanas a tu ritmo. Te cuesta menos tiempo del que ya pierdes en lo que elimina.",
        },
        {
          q: "¿Necesito suscripción de pago?",
          a: "Puedes empezar gratis. Donde ayude el plan de pago, te lo decimos antes de que gastes nada.",
        },
        {
          q: "Ya uso ChatGPT a diario.",
          a: "Suelen ser los que más sacan: llegan con tareas reales y ven cuánto siguen haciendo a mano.",
        },
        {
          q: "¿Qué pasa tras la solicitud?",
          a: "Una persona te escribe con las fechas y cómo entrar. Sin embudos ni llamadas.",
        },
      ],
    },
    pricing: {
      eyebrow: "Precio",
      title: "Un curso. Un precio.",
      sub: "Sin niveles ni extras. Todos se lo llevan todo, corrección incluida.",
      was: "$299",
      now: "$150",
      includes: [
        "Seis módulos en la plataforma",
        "Un control tras cada lección",
        "Tareas sobre tus casos reales",
        "Corrección por una persona",
        "Tus plantillas, para quedártelas",
      ],
      cta: "Solicitar acceso",
    },
    form: {
      title: "Solicitar acceso",
      sub: "Nombre y correo. Te responde una persona, normalmente el mismo día.",
      name: "Nombre",
      namePh: "María González",
      email: "Correo",
      emailPh: "tu@empresa.com",
      submit: "Enviar",
      sending: "Enviando…",
      success: "¡Gracias! Nos pondremos en contacto.",
      successSub: "Una persona te escribirá con los siguientes pasos.",
      errName: "Introduce tu nombre.",
      errEmail: "Introduce un correo válido.",
      errSend: "Algo ha fallado. Inténtalo otra vez.",
      privacy: "Solo usamos esto para contactarte. Sin listas de correo.",
    },
    footer: {
      tagline: "Promptea o perece.",
      rights: "Todos los derechos reservados.",
    },
  },
  ru: {
    label: "Русский",
    nav: {
      method: "Обучение",
      curriculum: "Программа",
      skills: "Навыки",
      pricing: "Цена",
      cta: "Получить доступ",
    },
    hero: {
      pill: "500+ выпускников · 2–4 недели",
      title: ["Через четыре недели", "вы будете поручать ИИ ", "то, что делаете руками", "."],
      sub: "Не видеокурс. Урок, задание на вашей настоящей работе, проверка живым преподавателем. На выходе — готовые заготовки, которые делают отчёты и письма за вас.",
      cta: "Получить доступ",
      ghost: "Как это работает",
      was: "$299",
      now: "$150",
      tags: ["ChatGPT", "Claude", "Gemini", "Без программирования"],
      gloss: "Prompta aut perire — с латыни «промпти или погибни». Промпт — это текст, которым вы объясняете нейросети, что вам нужно.",
      app: {
        heading: "заготовка 09",
        week: "урок 02",
        outLabel: "готовый ответ",
        result: [
          "Маржа выросла на 4% — за счёт двух крупных сделок",
          "Риск: один клиент даёт 40% выручки (с. 12)",
          "Решение: продлевать ли договор с подрядчиком",
        ],
        stack: ["заготовка 07", "заготовка 08"],
      },
    },
    pain: {
      eyebrow: "Знакомо?",
      title: "Вы знаете, что ИИ мог бы это сделать. И всё равно делаете сами.",
      items: [
        {
          q: "Смотрели видео про ИИ, а в пустом чате не знаете, что написать.",
          a: "Видео показывают кнопки. Никто не показывает, как довести вашу задачу до готового результата.",
        },
        {
          q: "Ответ приходит гладкий и не по делу. Переписываете сами.",
          a: "Дело не в ИИ, а в том, как вы просите. Этому учатся за пару часов.",
        },
        {
          q: "Каждый понедельник — тот же отчёт, та же сводка.",
          a: "Это можно отдать один раз и больше никогда не делать руками.",
        },
        {
          q: "Коллега успевает за час то, на что у вас уходит день.",
          a: "Он не умнее. У него есть заготовки. Свои вы соберёте за четыре недели.",
        },
      ],
    },
    mechanism: {
      eyebrow: "В чём разница",
      title: "Вы собираете заготовки. По одной за урок.",
      lede: "Приёмы забываются. Заготовка — нет. Один раз описали задачу, дальше просто запускаете: каждый понедельник, для каждого клиента.",
      pillars: [
        {
          n: "Делаете",
          title: "Заготовку под вашу задачу",
          text: "Ваш настоящий отчёт, ваше письмо, ваш договор. Не учебный пример.",
        },
        {
          n: "Проверяют",
          title: "Преподаватель находит ошибки",
          text: "Читает то, что вы собрали, и показывает, где это подведёт. Видео так не умеет.",
        },
        {
          n: "Остаётся",
          title: "Заготовка ваша навсегда",
          text: "Через месяц у вас их набор. Работают, даже когда вы забыли, как их делали.",
        },
      ],
      example: {
        label: "Вот как она выглядит",
        name: "Еженедельный отчёт для директора",
        lines: [
          "Ты готовишь отчёт для директора. Она читает 90 секунд.",
          "Я пришлю цифры за неделю. Дай: что изменилось и почему,",
          "один риск и одно решение, которое ждёт её.",
          "Одна страница, без прилагательных.",
        ],
        note: "Это всё. Обычный текст, написанный словами и сохранённый один раз. Каждый понедельник вы открываете его, вставляете свежие цифры и получаете готовый отчёт. К концу курса таких заготовок у вас девять — под ваши повторяющиеся задачи.",
      },
      close: "Поэтому нашими заготовками пользуются и через полгода после курса.",
    },
    scene: {
      eyebrow: "Четыре недели сверху",
      title: "Одна заготовка за урок. Девять к концу.",
      note: "Листайте дальше и смотрите, как они ложатся в стопку. Каждая — работа, которую вы делали руками, описанная один раз и оставшаяся у вас навсегда.",
      counter: "заготовок собрано",
    },
    demo: {
      eyebrow: "Посмотрите",
      title: "Вся разница — в том, как попросили",
      lede: "Та же нейросеть, та же задача. Слева и справа — обычный текст, который пишут словами прямо в чат. Выберите, что ближе вам.",
      badLabel: "Как пишет большинство",
      goodLabel: "Как напишете вы",
      resultLabel: "Ответ",
      note: "Никаких секретных слов. Просто понятное объяснение: кто читает, что важно, в каком виде нужен ответ.",
      tabs: [
        {
          id: "report",
          label: "Отчёт руководителю",
          bad: {
            prompt: "Сделай краткое содержание этого отчёта для директора.",
            result: "Восемь абзацев пересказа. Ни цифр, ни выводов. Переписываете сами.",
          },
          good: {
            prompt: [
              "Справка директору. Она читает 90 секунд и сначала спрашивает про деньги.",
              "Дай: три цифры, которые изменились, и почему.",
              "Два риска — со ссылкой на страницу.",
              "Одно решение, которое ждёт её.",
              "Одна страница.",
            ],
            result: "Страница, которая начинается с денег. Каждая цифра — со ссылкой на страницу. Отправляете как есть.",
          },
        },
        {
          id: "client",
          label: "Плохая новость клиенту",
          bad: {
            prompt: "Напиши клиенту, что сроки сдвигаются на две недели.",
            result: "Вежливые извинения без плана. Клиент звонит вашему руководителю.",
          },
          good: {
            prompt: [
              "Клиент ждал 14-го, будет 28-го. Причина: подвёл поставщик.",
              "Первая строка — новая дата и что клиент получит уже на этой неделе.",
              "Дальше причина одним предложением, без оправданий.",
              "В конце: что нужно от клиента и до какого числа.",
              "Восемь строк, спокойный тон.",
            ],
            result: "Письмо начинается с решения, а не с извинений. Клиент отвечает по делу.",
          },
        },
        {
          id: "contract",
          label: "Проверить договор",
          bad: {
            prompt: "Прочитай договор и скажи, что в нём не так.",
            result: "Пересказ пунктов и совет сходить к юристу. Читаете сами.",
          },
          good: {
            prompt: [
              "Я исполнитель. Бюджет 12 000 $, срок три месяца.",
              "Найди пункты, из-за которых я могу работать или платить сверх договора.",
              "Найди, где заказчик может расторгнуть без компенсации.",
              "По каждому: цитата, номер пункта и что предложить взамен.",
              "Нормальные пункты не упоминай.",
            ],
            result: "Шесть пунктов с цитатами и номерами. К каждому — готовая замена. Двадцать минут вместо вечера.",
          },
        },
      ],
    },
    method: {
      eyebrow: "Как проходит обучение",
      title: "Вас учат, а не выдают доступ",
      lede: "Обычные курсы дают папку с видео. Её не досматривают. Здесь следующий урок не откроется, пока не сделан предыдущий.",
      steps: [
        { n: "01", title: "Урок", text: "Короткий, по делу, вокруг одной задачи." },
        { n: "02", title: "Тест", text: "Не поняли — дальше не пустит." },
        { n: "03", title: "Задание", text: "На вашей настоящей работе, а не на выдуманном примере." },
        { n: "04", title: "Проверка", text: "Живой человек читает и правит то, что вы сделали." },
      ],
      platform: "Всё происходит на нашей платформе: уроки, задания, проверки, прогресс. С компьютера и с телефона, в удобные вам часы.",
      note: "Если нужна просто папка с видео — вам не сюда. Здесь придётся работать.",
    },
    curriculum: {
      eyebrow: "Программа",
      title: "Шесть модулей. После каждого что-то работает.",
      sub: "",
      modules: [
        {
          n: "01",
          title: "Как это работает",
          text: "Что умеют нейросети, чем отличаются и где уверенно врут.",
          result: "Знаете, чему верить, а что проверять.",
        },
        {
          n: "02",
          title: "Как просить",
          text: "Из чего состоит запрос, который срабатывает с первого раза.",
          result: "Ответ отправляете как есть.",
        },
        {
          n: "03",
          title: "Документы и таблицы",
          text: "Договоры, отчёты, счета, сканы и фотографии бумаг.",
          result: "Шестьдесят страниц превращаются в одну.",
        },
        {
          n: "04",
          title: "Свой помощник",
          text: "Помнит ваших клиентов и ваш стиль. Плюс голосовой ввод.",
          result: "Не объясняете всё заново каждое утро.",
        },
        {
          n: "05",
          title: "Рутина без вас",
          text: "Отчёты, сводки, разбор встреч, поиск информации.",
          result: "Понедельник: десять минут вместо утра.",
        },
        {
          n: "06",
          title: "Свои инструменты",
          text: "Маленькая программа под вашу задачу, без единой строчки кода.",
          result: "Делаете за вечер то, чего ждали от айтишников квартал.",
        },
      ],
    },
    outcomes: {
      eyebrow: "Навыки",
      title: "Девять вещей, которые вы будете уметь",
      sub: "Найдите свою — ту, из-за которой у вас регулярно горит вечер.",
      skills: [
        { title: "Отличать правду от выдумки", text: "ИИ уверенно придумывает цифры. Вы поймаете это до того, как отправите документ." },
        { title: "Получать нужное сразу", text: "Тот же запрос, объяснённый правильно. Переписывать не придётся." },
        { title: "Разбирать документы", text: "Договор, отчёт, счёт, скан: что важно, где подвох, чего не хватает." },
        { title: "Иметь помощника, который вас знает", text: "Он помнит ваших клиентов и делает сразу по-вашему." },
        { title: "Работать голосом", text: "Надиктовали по дороге — получили готовое письмо или список задач." },
        { title: "Снять с себя рутину", text: "Отчёты, сводки, разбор встреч делаются без вашего участия." },
        { title: "Проверять идеи без риска", text: "Ваш текст или цену сначала разносят выдуманные клиенты." },
        { title: "Собирать себе инструменты", text: "Калькулятор, бот или программа — за вечер, без программирования." },
        { title: "Перевести на это отдел", text: "Ставите то же самое команде и показываете результат в цифрах." },
      ],
      stats: [
        { v: "500+", l: "Выпускников" },
        { v: "2–4", l: "Недели" },
        { v: "100%", l: "Работ проверено" },
        { v: "0", l: "Строчек кода" },
      ],
    },
    testimonials: {
      eyebrow: "Выпускники",
      title: "Что говорят после курса",
      items: [] as { quote: string; name: string; role: string; result: string }[],
    },
    cost: {
      eyebrow: "Честно",
      title: "Отложите — ничего страшного не случится. В этом и проблема.",
      text: "Потеря не приходит счётом. Она приходит потерянными вечерами и коллегой, который тихо стал быстрее вас. Два часа в неделю — это тринадцать рабочих дней в год. Курс стоит меньше одного такого дня.",
      cta: "Начать на этой неделе",
    },
    faq: {
      eyebrow: "Вопросы",
      title: "О чём спрашивают чаще всего",
      items: [
        {
          q: "А если у меня не получится?",
          a: "Задания проверяет человек — если не выходит, вам покажут, где именно, и дадут переделать. И курс короткий: если через неделю поймёте, что это не ваше, вы потеряете неделю, а не полгода.",
        },
        {
          q: "Это же есть бесплатно на YouTube.",
          a: "Есть — кусками, без порядка, и без человека, который скажет, что вы сделали не так. Вы платите за порядок, задания на своей работе и проверку. Если у вас есть 200 свободных часов — YouTube честно работает.",
        },
        {
          q: "Я совсем не технарь.",
          a: "Программирования здесь нет нигде. Умеете пользоваться браузером — справитесь. Тяжело только тем, кто не делает задания.",
        },
        {
          q: "У меня нет времени.",
          a: "Уроки короткие, всё занимает 2–4 недели в вашем темпе. Вы тратите меньше, чем уже теряете на задачах, которые курс убирает.",
        },
        {
          q: "Нужна платная подписка?",
          a: "Начать можно бесплатно. Где платная удобнее — скажем заранее, до того как вы что-то потратите.",
        },
        {
          q: "Я и так пользуюсь ChatGPT каждый день.",
          a: "Такие обычно выносят больше всех: приходят с настоящими задачами и видят, сколько всё ещё делают руками.",
        },
        {
          q: "Что после заявки?",
          a: "Вам напишет человек: даты старта и как попасть на обучение. Без автоворонок и звонков.",
        },
      ],
    },
    pricing: {
      eyebrow: "Цена",
      title: "Одна программа. Одна цена.",
      sub: "Без тарифов и доплат. Все получают всё, включая проверку работ.",
      was: "$299",
      now: "$150",
      includes: [
        "Шесть модулей на платформе",
        "Тест после каждого урока",
        "Задания на ваших настоящих задачах",
        "Проверка и разбор живым человеком",
        "Ваши заготовки — остаются у вас",
      ],
      cta: "Оставить заявку",
    },
    form: {
      title: "Оставить заявку",
      sub: "Имя и почта. Вам ответит человек — обычно в тот же день.",
      name: "Имя",
      namePh: "Мария Иванова",
      email: "Почта",
      emailPh: "you@company.com",
      submit: "Отправить",
      sending: "Отправляем…",
      success: "Спасибо! Мы свяжемся с вами.",
      successSub: "Человек напишет вам на почту и расскажет, что дальше.",
      errName: "Укажите имя.",
      errEmail: "Укажите корректную почту.",
      errSend: "Что-то пошло не так. Попробуйте ещё раз.",
      privacy: "Данные нужны только чтобы связаться с вами. Никаких рассылок.",
    },
    footer: {
      tagline: "Промпти или погибни.",
      rights: "Все права защищены.",
    },
  },
};

export type Copy = (typeof content)["en"];
