export type Lang = "en" | "es" | "ru";

export const content = {
  en: {
    label: "English",
    nav: {
      method: "How it works",
      curriculum: "Course",
      skills: "Skills",
      pricing: "Price",
      cta: "Get access",
    },
    hero: {
      pill: "500+ graduates · your access does not expire",
      title: ["Learn to hand AI", "the work you are still ", "doing by hand", "."],
      sub: "From knowing nothing to running your own assistants and automations. A lesson, a task on your real work, and a teacher who reads what you built. No programming, at your own pace.",
      cta: "Get access",
      ghost: "What's inside",
      was: "$299",
      now: "$150",
      save: "you save $149",
      tags: ["ChatGPT", "Claude", "Gemini", "No coding"],
      gloss: "Prompta aut perire is Latin for “prompt or perish”. A prompt is the plain text you write to tell an AI what you need.",
      app: {
        heading: "setup 09",
        week: "lesson 02",
        outLabel: "finished answer",
        result: [
          "Margin up 4% — two large deals carried it",
          "Risk: one client is 40% of revenue (p. 12)",
          "Decision: renew the contractor or not",
        ],
        stack: ["setup 07", "setup 08"],
      },
    },
    field: {
      tasks: [
        "Weekly report",
        "Email to a client",
        "Contract checked",
        "Meeting notes",
        "Proposal drafted",
        "Objection answered",
        "Clause found",
        "Product copy",
        "Price worked out",
        "Invoice checked",
        "Week planned",
        "Same question, answered",
        "Documents reconciled",
        "Site copy",
        "Sources read",
        "Follow-up sent",
      ],
    },
    authority: {
      eyebrow: "Who teaches it",
      line: "The course is taught by an instructor who has worked with IBM, Amazon, OpenAI and Anthropic.",
      items: ["IBM", "Amazon", "OpenAI", "Anthropic"],
      note: "The same person reads and corrects your work. Not theory out of a manual — practice from inside the companies building this.",
    },
    who: {
      eyebrow: "Who it's for",
      title: "Everyone's job is different. The routine is the same.",
      sub: "Find yourself here. Inside the course you do the exercises on your own tasks, not on someone else's.",
      items: [
        { role: "Managers and team leads", task: "The weekly report, meeting notes, the summary nobody has time to write." },
        { role: "Sales and account people", task: "A proposal shaped to one client, an answer to an objection, the follow-up after a call." },
        { role: "Finance and legal", task: "Checking a contract, reconciling documents, finding one clause in a hundred pages." },
        { role: "Doctors, teachers, researchers", task: "Materials, plans, going through sources, answering the same questions for the tenth time." },
        { role: "Business owners", task: "Product descriptions, site copy, pricing, testing an idea before you spend on it." },
        { role: "Anyone working alone", task: "All of the above. The assistant you cannot afford to hire." },
      ],
    },
    pain: {
      eyebrow: "Sound familiar?",
      title: "You know AI could do this. You are still doing it yourself.",
      items: [
        {
          q: "You watched the videos, then sat in an empty chat with nothing to type.",
          a: "Videos show you buttons. Nobody shows you how to take your task all the way to a finished result.",
        },
        {
          q: "The answer comes back smooth and useless. You rewrite it yourself.",
          a: "That is not the AI. It is how you asked. It takes a couple of hours to learn.",
        },
        {
          q: "Every Monday, the same report. The same summary.",
          a: "You can hand that over once and never do it by hand again.",
        },
        {
          q: "A colleague does in an hour what takes you a day.",
          a: "They are not smarter. They have setups saved. You will build your own here.",
        },
      ],
    },
    mechanism: {
      eyebrow: "The difference",
      title: "You build setups. One per lesson.",
      lede: "Tricks are forgotten. A setup is not. You describe the job once, then you just run it: every Monday, for every client.",
      pillars: [
        {
          n: "You build",
          title: "A setup for your own job",
          text: "Your real report, your email, your contract. Not a teaching example.",
        },
        {
          n: "Checked",
          title: "A teacher finds what breaks",
          text: "She reads what you built and shows you where it will fail. A video cannot do that.",
        },
        {
          n: "You keep",
          title: "The setup stays yours",
          text: "At the end you have a set of them. They work even when you have forgotten how you made them.",
        },
      ],
      example: {
        label: "Here's what one looks like",
        name: "Weekly report for my director",
        askLabel: "You write this once, in plain words",
        lines: [
          "You're writing a report for my director. She reads for 90 seconds.",
          "I'll paste this week's figures. Give me: what changed and why,",
          "one risk, and one decision waiting on her.",
          "One page, no adjectives.",
        ],
        outLabel: "And every Monday you get this back",
        out: [
          "Margin: 18% → 22%. Two large deals in October, p. 4.",
          "Churn: 3% → 7%. Delivery delays at the Kazan warehouse, p. 9.",
          "Average order: $560 → $640, p. 6.",
          "Risk: one client is 40% of revenue. Lose them, lose a third of the plan, p. 12.",
          "Waiting on you: renew the contractor or not. Due the 30th.",
        ],
        before: "Before: Tuesday evening pulling the figures together and choosing the words.",
        after: "After: paste the figures, report done in half a minute.",
        note: "That's it. Ordinary text, written in plain words and saved once. By the end of the course you have nine of these, built around the work you repeat.",
      },
      close: "That's why graduates are still using theirs six months later.",
    },
    scene: {
      eyebrow: "What you learn",
      title: "Every lesson ends with something that works.",
      note: "Keep scrolling and watch it add up. Nine abilities across six parts — from how any of this actually works to agents that run the job without you.",
      counter: "abilities gained",
    },
    demo: {
      eyebrow: "See it",
      title: "The whole difference is in how you asked",
      lede: "Same AI, same job. Both sides are ordinary text, typed straight into the chat. Pick whichever is closest to your work.",
      badLabel: "How most people write",
      goodLabel: "How you will write",
      resultLabel: "Answer",
      note: "No secret words. Just a clear explanation: who reads it, what matters, and what shape the answer should take.",
      tabs: [
        {
          id: "report",
          label: "Report to a boss",
          bad: {
            prompt: "Summarise this report for my director.",
            result: [
              "The company continues to demonstrate steady momentum.",
              "The sales team held a number of productive meetings.",
              "The supplier situation remains under control.",
              "Continued monitoring of key indicators is recommended.",
            ],
            verdict: "Not one figure. You rewrite it yourself — forty minutes.",
          },
          good: {
            prompt: [
              "A brief for my director. She reads for 90 seconds and asks about money first.",
              "Give me: three figures that moved, and why.",
              "Two risks, each with a page reference.",
              "One decision that is waiting on her.",
              "One page.",
            ],
            result: [
              "Margin: 18% → 22%. Two large deals in October, p. 4.",
              "Churn: 3% → 7%. Delivery delays at the Kazan warehouse, p. 9.",
              "Average order: $560 → $640, p. 6.",
              "Risk: one client is 40% of revenue, p. 12.",
              "Waiting on you: renew the contractor or not, due the 30th.",
            ],
            verdict: "You send it as it is. Half a minute.",
          },
        },
        {
          id: "client",
          label: "Bad news to a client",
          bad: {
            prompt: "Write to the client that the deadline moves by two weeks.",
            result: [
              "Dear Mr Harper,",
              "We regret to inform you that, due to circumstances beyond",
              "our control, the project timeline has shifted.",
              "We sincerely apologise and appreciate your understanding.",
            ],
            verdict: "No date, no plan. The client calls your boss.",
          },
          good: {
            prompt: [
              "Client expected the 14th, it will be the 28th. Cause: a supplier let us down.",
              "First line: the new date and what they get this week.",
              "Then the cause in one sentence, no excuses.",
              "End with what we need from them and by when.",
              "Eight lines, calm tone.",
            ],
            result: [
              "James, the new delivery date is 28 October.",
              "Layouts and copy come to you Thursday — you can work with them now.",
              "Cause: our supplier missed a shipment; we found a replacement in three days.",
              "What we need: your sign-off on the layouts by the 21st.",
              "Later than that and the 28th moves too — I'll tell you straight away.",
            ],
            verdict: "The client replies about the work, not to your boss.",
          },
        },
        {
          id: "contract",
          label: "Check a contract",
          bad: {
            prompt: "Read this contract and tell me what's wrong with it.",
            result: [
              "The contract is broadly standard in its construction.",
              "Pay attention to the payment and timeline sections.",
              "Some wording could be clarified further.",
              "We recommend consulting a qualified lawyer.",
            ],
            verdict: "You read the contract yourself. An evening.",
          },
          good: {
            prompt: [
              "I am the contractor. Budget $12,000, three months.",
              "Find the clauses that could make me work or pay beyond the contract.",
              "Find where the client can walk away without compensation.",
              "For each: the quote, the clause number, and what to propose instead.",
              "Skip the clauses that are fine.",
            ],
            result: [
              "4.2 — \"revisions continue until the Client is fully satisfied\".",
              "→ That is work without end. Replace with: \"no more than two rounds\".",
              "7.1 — termination at any time with no payment for work done.",
              "→ Replace with: \"payment for work completed as at the termination date\".",
              "9.3 — penalty of 0.5% per day with no upper limit.",
              "→ Replace with: \"capped at 10% of the contract value\".",
            ],
            verdict: "Three traps, numbered, each with a replacement. Twenty minutes.",
          },
        },
      ],
    },
    method: {
      eyebrow: "How the learning works",
      title: "You are taught, not handed a login",
      lede: "Most courses give you a folder of videos. Nobody finishes those. Here the next lesson stays shut until the last one is done.",
      steps: [
        { n: "01", title: "Lesson", text: "Short, to the point, built around one job." },
        { n: "02", title: "Check", text: "Didn't follow it? You don't move on." },
        { n: "03", title: "Task", text: "On your real work, not an invented example." },
        { n: "04", title: "Review", text: "A person reads what you did and corrects it." },
      ],
      ui: {
        brand: "Prompta · learning platform",
        week: "Track 2 · Beginner",
        progress: "62%",
        moduleLabel: "Beginner · Asking properly",
        lessons: [
          { state: "done", title: "What the model can and cannot do", meta: "passed" },
          { state: "done", title: "The four parts of a working request", meta: "passed" },
          { state: "now", title: "Your weekly report", meta: "in review" },
          { state: "lock", title: "Testing an idea on invented clients", meta: "opens after review" },
        ],
        lessonTitle: "Lesson 5 · Your weekly report",
        yours: "Your setup",
        yourLines: [
          "You're writing a report for my director. She reads for 90 seconds.",
          "Give me: what changed and why, one risk and one decision.",
        ],
        reviewBy: "Review · your teacher",
        review:
          "Good structure. Two fixes: say where the figures come from, or the model will invent them. And ask for the risk with a page reference. Resubmit and you're done.",
        actions: ["Fix and resubmit", "Save to my library"],
      },
      platform: "It all happens on our own platform: lessons, tasks, reviews, progress. On a laptop or a phone, at whatever hours suit you.",
      note: "If what you want is a folder of videos, this is not it. Here you have to do the work.",
    },
    curriculum: {
      eyebrow: "The course",
      title: "Six parts. From knowing nothing to running agents.",
      sub: "Four tracks in order, a bonus for people with no time, and a plan for what comes after.",
      modules: [
        {
          n: "01",
          title: "Base",
          text: "What a neural network actually is, and what tokens, hallucinations, working from your own documents and agents really mean — in plain words, no formulas.",
          result: "You know what to trust and what to check.",
        },
        {
          n: "02",
          title: "Beginner",
          text: "ChatGPT and Claude with confidence: threads, files, images, voice — and what must never go into a chat window.",
          result: "You work on your own, without looking things up.",
        },
        {
          n: "03",
          title: "Intermediate",
          text: "Asking properly: from a single question to reusable setups, your own library, and assistants that know your company.",
          result: "You send the answer as it is.",
        },
        {
          n: "04",
          title: "Advanced",
          text: "Automation and agents: schedules, browser agents, no-code dashboards and calculators, several agents working together — and where the risks sit.",
          result: "The routine runs without you.",
        },
        {
          n: "05",
          title: "Bonus · 49 minutes",
          text: "A condensed walkthrough for executives with no time: what to decide, what to delegate, what to watch.",
          result: "The whole picture in one evening.",
        },
        {
          n: "06",
          title: "What comes next",
          text: "Rolling this out to a team: where AI must not be trusted, what to measure, how to keep it under control.",
          result: "You show the effect in numbers.",
        },
      ],
    },
    outcomes: {
      eyebrow: "Skills",
      title: "Nine things you will be able to do",
      sub: "Find yours — the one that regularly costs you an evening.",
      skills: [
        { title: "Tell fact from invention", text: "AI invents figures and sources with total confidence. You will catch it before the document goes out." },
        { title: "Get it right first time", text: "The same request, explained properly. No rewriting afterwards." },
        { title: "Get through documents", text: "Contract, report, invoice, scan: what matters, where the catch is, what's missing — plus deep research that comes back with sources." },
        { title: "Have a helper that knows you", text: "It knows your company, your clients and your style, and answers your way from the start." },
        { title: "Work by voice and screen", text: "Dictate on the way in. Share your screen and explain a job without typing a word." },
        { title: "Hand over the routine", text: "Reports, summaries and meeting notes run on a schedule, without you in the loop." },
        { title: "Test ideas risk-free", text: "Your copy or your pricing gets torn apart by invented customers first." },
        { title: "Build your own tools", text: "A dashboard, a calculator, a small app — in an evening, without a line of code." },
        { title: "Take your team with you", text: "You set the same thing up for the team and show the result in numbers." },
      ],
      stats: [
        { v: "500+", l: "Graduates" },
        { v: "6", l: "Parts" },
        { v: "100%", l: "Work reviewed" },
        { v: "0", l: "Lines of code" },
      ],
    },
    testimonials: {
      eyebrow: "Graduates",
      title: "What they say afterwards",
      items: [] as { quote: string; name: string; role: string; result: string }[],
    },
    cost: {
      eyebrow: "Straight talk",
      title: "Put it off and nothing bad happens. That is the problem.",
      text: "The loss never arrives as a bill. It arrives as lost evenings and a colleague who quietly got faster than you. Two hours a week is thirteen working days a year. The course costs less than one of them.",
      cta: "Start this week",
    },
    faq: {
      eyebrow: "Questions",
      title: "What people ask most",
      items: [
        {
          q: "What if I can't do it?",
          a: "A person reads your work — if it isn't landing, you're shown exactly where and given another go. And you start at the very bottom: if you have never used AI at all, the first track is written for you.",
        },
        {
          q: "Who teaches it?",
          a: "An instructor who has worked with IBM, Amazon, OpenAI and Anthropic. She is also the one who reads and corrects your work.",
        },
        {
          q: "This is all free on YouTube.",
          a: "It is — in pieces, in no order, and with nobody to tell you what you got wrong. You are paying for the order, the tasks on your own work, and the review. If you have 200 spare hours, YouTube genuinely works.",
        },
        {
          q: "I'm not technical at all.",
          a: "There is no programming anywhere in this. If you can use a browser, you can do it. The only people who struggle are the ones who skip the tasks.",
        },
        {
          q: "I don't have time.",
          a: "You go at your own pace and your access stays. If time is genuinely gone, start with the 49-minute bonus: it gives you the whole picture in one evening.",
        },
        {
          q: "Do I need a paid subscription?",
          a: "You can start for free. Where a paid plan helps, we say so in advance, before you spend anything.",
        },
        {
          q: "I already use ChatGPT every day.",
          a: "Then start at the Intermediate track. People like you usually take the most out of it: they arrive with real work and see how much they are still doing by hand.",
        },
        {
          q: "What happens after I apply?",
          a: "A person emails you: when you can start and how to get in. No funnels, no calls.",
        },
      ],
    },
    pricing: {
      eyebrow: "Price",
      title: "One course. One price.",
      sub: "No tiers, no upsells. Everyone gets everything, review included.",
      was: "$299",
      now: "$150",
      includes: [
        "Six parts: from the basics to agents",
        "Tasks on your own real work",
        "Review and correction by a live teacher",
        "Bonus: 49 minutes for executives",
        "Your access and your setups stay yours",
      ],
      cta: "Apply now",
    },
    form: {
      title: "Apply now",
      sub: "Name and email. A person replies, usually the same day.",
      name: "Name",
      namePh: "Alex Morgan",
      email: "Email",
      emailPh: "you@company.com",
      submit: "Send",
      sending: "Sending…",
      success: "Thank you! We'll be in touch.",
      successSub: "A person will email you and explain what happens next.",
      errName: "Please enter your name.",
      errEmail: "Please enter a valid email.",
      errSend: "Something went wrong. Please try again.",
      privacy: "We only use this to contact you. No mailing lists.",
    },
    footer: {
      tagline: "Prompt or perish.",
      rights: "All rights reserved.",
    },
  },

  es: {
    label: "Español",
    nav: {
      method: "Cómo funciona",
      curriculum: "Programa",
      skills: "Habilidades",
      pricing: "Precio",
      cta: "Obtener acceso",
    },
    hero: {
      pill: "500+ graduados · el acceso no caduca",
      title: ["Delegue a la IA", "el trabajo que todavía ", "hace a mano", "."],
      sub: "Desde no saber nada hasta manejar sus propios asistentes y automatizaciones. Una lección, una tarea sobre su trabajo real y una profesora que lee lo que usted construyó. Sin programar, a su ritmo.",
      cta: "Obtener acceso",
      ghost: "Qué incluye",
      was: "$299",
      now: "$150",
      save: "ahorra $149",
      tags: ["ChatGPT", "Claude", "Gemini", "Sin programar"],
      gloss: "Prompta aut perire es latín: «pide o perece». Un prompt es el texto corriente con el que usted le explica a la IA lo que necesita.",
      app: {
        heading: "plantilla 09",
        week: "lección 02",
        outLabel: "respuesta lista",
        result: [
          "Margen +4%: lo sostuvieron dos operaciones grandes",
          "Riesgo: un cliente es el 40% de los ingresos (p. 12)",
          "Decisión: renovar o no al proveedor",
        ],
        stack: ["plantilla 07", "plantilla 08"],
      },
    },
    field: {
      tasks: [
        "Informe semanal",
        "Correo al cliente",
        "Contrato revisado",
        "Acta de reunión",
        "Propuesta redactada",
        "Objeción respondida",
        "Cláusula encontrada",
        "Ficha de producto",
        "Precio calculado",
        "Factura revisada",
        "Semana planificada",
        "La pregunta de siempre",
        "Documentos cuadrados",
        "Textos de la web",
        "Fuentes revisadas",
        "Correo de seguimiento",
      ],
    },
    authority: {
      eyebrow: "Quién enseña",
      line: "El curso lo imparte una profesora que ha trabajado con IBM, Amazon, OpenAI y Anthropic.",
      items: ["IBM", "Amazon", "OpenAI", "Anthropic"],
      note: "Es la misma persona que lee y corrige sus tareas. No es teoría de manual: es práctica de dentro de las empresas que construyen esto.",
    },
    who: {
      eyebrow: "Para quién es",
      title: "El trabajo de cada uno es distinto. La rutina es la misma.",
      sub: "Búsquese aquí. Dentro del curso hace los ejercicios sobre sus propias tareas, no sobre las de otro.",
      items: [
        { role: "Jefes y responsables de equipo", task: "El informe semanal, las actas, el resumen que nadie tiene tiempo de escribir." },
        { role: "Comercial y atención al cliente", task: "Una propuesta a medida, una respuesta a una objeción, el correo después de la llamada." },
        { role: "Finanzas y jurídico", task: "Revisar un contrato, cuadrar documentos, encontrar una cláusula en cien páginas." },
        { role: "Médicos, docentes, investigadores", task: "Materiales, planes, revisar fuentes, responder lo mismo por décima vez." },
        { role: "Dueños de negocio", task: "Fichas de producto, textos para la web, precios, probar una idea antes de gastar en ella." },
        { role: "Quien trabaja solo", task: "Todo lo anterior. El ayudante que no se puede permitir contratar." },
      ],
    },
    pain: {
      eyebrow: "¿Le suena?",
      title: "Sabe que la IA podría hacerlo. Y lo sigue haciendo usted.",
      items: [
        {
          q: "Vio los vídeos y luego se quedó ante un chat vacío sin saber qué escribir.",
          a: "Los vídeos enseñan botones. Nadie enseña a llevar su tarea hasta un resultado terminado.",
        },
        {
          q: "La respuesta llega pulida e inútil. La reescribe usted.",
          a: "No es la IA. Es cómo se lo pidió. Eso se aprende en un par de horas.",
        },
        {
          q: "Cada lunes, el mismo informe. El mismo resumen.",
          a: "Eso se delega una vez y no se vuelve a hacer a mano.",
        },
        {
          q: "Un compañero hace en una hora lo que a usted le lleva un día.",
          a: "No es más listo. Tiene plantillas guardadas. Aquí construirá las suyas.",
        },
      ],
    },
    mechanism: {
      eyebrow: "La diferencia",
      title: "Usted construye plantillas. Una por lección.",
      lede: "Los trucos se olvidan. Una plantilla no. Describe el trabajo una vez y luego solo la ejecuta: cada lunes, para cada cliente.",
      pillars: [
        {
          n: "Construye",
          title: "Una plantilla para su propio trabajo",
          text: "Su informe real, su correo, su contrato. No un ejemplo de clase.",
        },
        {
          n: "Se revisa",
          title: "Una profesora encuentra lo que falla",
          text: "Lee lo que usted construyó y le muestra dónde se va a romper. Un vídeo no puede hacer eso.",
        },
        {
          n: "Se queda",
          title: "La plantilla es suya para siempre",
          text: "Al final tiene un juego entero. Funcionan incluso cuando ya olvidó cómo las hizo.",
        },
      ],
      example: {
        label: "Así es una de ellas",
        name: "Informe semanal para mi directora",
        askLabel: "Esto lo escribe una vez, con palabras normales",
        lines: [
          "Escribes un informe para mi directora. Ella lee 90 segundos.",
          "Te pasaré las cifras de la semana. Dame: qué cambió y por qué,",
          "un riesgo y una decisión que la espera.",
          "Una página, sin adjetivos.",
        ],
        outLabel: "Y cada lunes recibe esto",
        out: [
          "Margen: 18% → 22%. Dos operaciones grandes en octubre, p. 4.",
          "Fuga de clientes: 3% → 7%. Retrasos en el almacén, p. 9.",
          "Ticket medio: $560 → $640, p. 6.",
          "Riesgo: un cliente es el 40% de los ingresos. Si se va, cae un tercio del plan, p. 12.",
          "Le espera a usted: renovar o no al proveedor. Antes del día 30.",
        ],
        before: "Antes: la tarde del martes juntando cifras y buscando cómo decirlo.",
        after: "Ahora: pega las cifras y el informe sale en medio minuto.",
        note: "Eso es todo. Texto corriente, escrito con palabras normales y guardado una vez. Al terminar el curso tiene nueve, hechas alrededor del trabajo que repite.",
      },
      close: "Por eso los graduados siguen usando las suyas seis meses después.",
    },
    scene: {
      eyebrow: "Lo que aprende",
      title: "Cada lección termina con algo que funciona.",
      note: "Siga bajando y mírelo sumarse. Nueve capacidades en seis partes — desde cómo funciona todo esto hasta agentes que hacen el trabajo sin usted.",
      counter: "capacidades logradas",
    },
    demo: {
      eyebrow: "Véalo",
      title: "Toda la diferencia está en cómo lo pidió",
      lede: "La misma IA, el mismo encargo. Los dos lados son texto corriente, escrito directamente en el chat. Elija lo más parecido a su trabajo.",
      badLabel: "Como escribe la mayoría",
      goodLabel: "Como escribirá usted",
      resultLabel: "Respuesta",
      note: "Ninguna palabra secreta. Solo una explicación clara: quién lo lee, qué importa y en qué forma hace falta la respuesta.",
      tabs: [
        {
          id: "report",
          label: "Informe a dirección",
          bad: {
            prompt: "Resume este informe para mi directora.",
            result: [
              "La empresa mantiene una dinámica estable.",
              "El equipo comercial celebró varias reuniones productivas.",
              "La situación con los proveedores sigue bajo control.",
              "Se recomienda continuar el seguimiento de los indicadores.",
            ],
            verdict: "Ni una cifra. Lo reescribe usted: cuarenta minutos.",
          },
          good: {
            prompt: [
              "Un resumen para mi directora. Lee 90 segundos y pregunta primero por el dinero.",
              "Dame: tres cifras que se movieron, y por qué.",
              "Dos riesgos, cada uno con la página.",
              "Una decisión que la está esperando.",
              "Una página.",
            ],
            result: [
              "Margen: 18% → 22%. Dos operaciones grandes en octubre, p. 4.",
              "Fuga de clientes: 3% → 7%. Retrasos en el almacén, p. 9.",
              "Ticket medio: $560 → $640, p. 6.",
              "Riesgo: un cliente es el 40% de los ingresos, p. 12.",
              "Le espera a ella: renovar o no al proveedor, antes del día 30.",
            ],
            verdict: "Lo envía tal cual. Medio minuto.",
          },
        },
        {
          id: "client",
          label: "Mala noticia a un cliente",
          bad: {
            prompt: "Escribe al cliente que el plazo se mueve dos semanas.",
            result: [
              "Estimado Sr. Herrera:",
              "Lamentamos comunicarle que, por circunstancias ajenas",
              "a nuestra voluntad, los plazos del proyecto se desplazan.",
              "Le pedimos disculpas y agradecemos su comprensión.",
            ],
            verdict: "Sin fecha y sin plan. El cliente llama a su jefe.",
          },
          good: {
            prompt: [
              "El cliente esperaba el 14, será el 28. Causa: falló un proveedor.",
              "Primera línea: la nueva fecha y qué recibe esta misma semana.",
              "Después la causa en una frase, sin excusas.",
              "Al final: qué necesitamos de él y para cuándo.",
              "Ocho líneas, tono tranquilo.",
            ],
            result: [
              "Javier, la nueva fecha de entrega es el 28 de octubre.",
              "Los diseños y los textos te llegan el jueves: ya puedes trabajar con ellos.",
              "Causa: el proveedor falló un envío; encontramos recambio en tres días.",
              "Necesitamos de ti: el visto bueno a los diseños antes del 21.",
              "Si llega más tarde, el 28 también se mueve, y te lo diré enseguida.",
            ],
            verdict: "El cliente responde sobre el trabajo, no llama a su jefe.",
          },
        },
        {
          id: "contract",
          label: "Revisar un contrato",
          bad: {
            prompt: "Lee este contrato y dime qué está mal.",
            result: [
              "El contrato está redactado de forma bastante estándar.",
              "Preste atención a los apartados de pago y plazos.",
              "Algunas formulaciones podrían precisarse mejor.",
              "Recomendamos consultar con un abogado.",
            ],
            verdict: "Se lee el contrato usted. Una tarde.",
          },
          good: {
            prompt: [
              "Soy el proveedor. Presupuesto $12 000, tres meses.",
              "Busca las cláusulas que puedan hacerme trabajar o pagar por encima del contrato.",
              "Busca dónde el cliente puede rescindir sin compensación.",
              "De cada una: la cita, el número de cláusula y qué proponer en su lugar.",
              "No menciones las cláusulas que están bien.",
            ],
            result: [
              "4.2 — «las correcciones siguen hasta la plena satisfacción del Cliente».",
              "→ Es trabajo sin fin. Cambiar por: «no más de dos rondas de correcciones».",
              "7.1 — rescisión en cualquier momento sin pagar lo ejecutado.",
              "→ Cambiar por: «pago de lo realmente ejecutado a la fecha de rescisión».",
              "9.3 — penalización del 0,5% diario, sin límite superior.",
              "→ Cambiar por: «con un máximo del 10% del importe del contrato».",
            ],
            verdict: "Tres trampas, numeradas y con recambio. Veinte minutos.",
          },
        },
      ],
    },
    method: {
      eyebrow: "Cómo se aprende",
      title: "Aquí se le enseña, no se le da una clave",
      lede: "Los cursos normales le dan una carpeta de vídeos. Nadie los termina. Aquí la lección siguiente no se abre hasta terminar la anterior.",
      steps: [
        { n: "01", title: "Lección", text: "Corta, al grano, alrededor de un solo encargo." },
        { n: "02", title: "Control", text: "¿No lo entendió? No pasa de ahí." },
        { n: "03", title: "Tarea", text: "Sobre su trabajo real, no sobre un ejemplo inventado." },
        { n: "04", title: "Revisión", text: "Una persona lee lo que hizo y lo corrige." },
      ],
      ui: {
        brand: "Prompta · plataforma de aprendizaje",
        week: "Nivel 2 · Beginner",
        progress: "62%",
        moduleLabel: "Beginner · Cómo pedir",
        lessons: [
          { state: "done", title: "Qué puede y qué no puede el modelo", meta: "superado" },
          { state: "done", title: "Las cuatro partes de una petición que funciona", meta: "superado" },
          { state: "now", title: "Su informe semanal", meta: "en revisión" },
          { state: "lock", title: "Probar una idea con clientes inventados", meta: "se abre tras la revisión" },
        ],
        lessonTitle: "Lección 5 · Su informe semanal",
        yours: "Su plantilla",
        yourLines: [
          "Escribes un informe para mi directora. Ella lee 90 segundos.",
          "Dame: qué cambió y por qué, un riesgo y una decisión.",
        ],
        reviewBy: "Revisión · su profesora",
        review:
          "Buena estructura. Dos correcciones: diga de dónde salen las cifras o el modelo se las inventará. Y pida el riesgo con el número de página. Reenvíelo y listo.",
        actions: ["Corregir y reenviar", "Guardar en mi biblioteca"],
      },
      platform: "Todo ocurre en nuestra propia plataforma: lecciones, tareas, revisiones, progreso. Desde el ordenador o el móvil, a las horas que le vengan bien.",
      note: "Si lo que quiere es una carpeta de vídeos, este no es su sitio. Aquí hay que trabajar.",
    },
    curriculum: {
      eyebrow: "Programa",
      title: "Seis partes. De no saber nada a manejar agentes.",
      sub: "Cuatro niveles en orden, un bonus para quien no tiene tiempo y un plan para lo que viene después.",
      modules: [
        {
          n: "01",
          title: "Base",
          text: "Qué es realmente una red neuronal y qué significan tokens, alucinaciones, trabajar con sus propios documentos y agentes — en palabras normales, sin fórmulas.",
          result: "Sabe qué creer y qué comprobar.",
        },
        {
          n: "02",
          title: "Beginner",
          text: "ChatGPT y Claude con soltura: hilos, archivos, imágenes, voz — y qué no debe entrar nunca en un chat.",
          result: "Trabaja solo, sin ir a buscar cómo se hace.",
        },
        {
          n: "03",
          title: "Intermediate",
          text: "Pedir bien: de una pregunta suelta a plantillas reutilizables, su propia biblioteca y asistentes que conocen su empresa.",
          result: "Envía la respuesta tal cual.",
        },
        {
          n: "04",
          title: "Advanced",
          text: "Automatización y agentes: horarios, agentes de navegador, paneles y calculadoras sin código, varios agentes trabajando juntos — y dónde están los riesgos.",
          result: "La rutina corre sin usted.",
        },
        {
          n: "05",
          title: "Bonus · 49 minutos",
          text: "Un recorrido condensado para directivos sin tiempo: qué decidir, qué delegar y qué vigilar.",
          result: "El cuadro completo en una tarde.",
        },
        {
          n: "06",
          title: "Qué viene después",
          text: "Llevarlo al equipo: dónde no se puede confiar en la IA, qué medir y cómo mantenerlo bajo control.",
          result: "Enseña el efecto en números.",
        },
      ],
    },
    outcomes: {
      eyebrow: "Habilidades",
      title: "Nueve cosas que sabrá hacer",
      sub: "Busque la suya: esa que le cuesta una tarde cada semana.",
      skills: [
        { title: "Distinguir el dato del invento", text: "La IA inventa cifras y fuentes con total aplomo. Usted lo detectará antes de enviar el documento." },
        { title: "Acertar a la primera", text: "La misma petición, explicada como toca. Sin reescribir después." },
        { title: "Atravesar documentos", text: "Contrato, informe, factura, escaneo: qué importa, dónde está la trampa, qué falta — y búsquedas a fondo que vuelven con fuentes." },
        { title: "Tener un ayudante que le conoce", text: "Conoce su empresa, sus clientes y su estilo, y responde a su manera desde el principio." },
        { title: "Trabajar con voz y pantalla", text: "Dicte de camino al trabajo. Comparta la pantalla y explique un encargo sin escribir una palabra." },
        { title: "Quitarse la rutina", text: "Informes, resúmenes y actas salen solos, en su horario, sin usted en medio." },
        { title: "Probar ideas sin riesgo", text: "Su texto o su precio lo destrozan primero unos clientes inventados." },
        { title: "Construirse herramientas", text: "Un panel, una calculadora, una pequeña app — en una tarde, sin una línea de código." },
        { title: "Llevarse al equipo", text: "Monta lo mismo para el equipo y enseña el resultado en números." },
      ],
      stats: [
        { v: "500+", l: "Graduados" },
        { v: "6", l: "Partes" },
        { v: "100%", l: "Trabajos revisados" },
        { v: "0", l: "Líneas de código" },
      ],
    },
    testimonials: {
      eyebrow: "Graduados",
      title: "Lo que dicen al terminar",
      items: [] as { quote: string; name: string; role: string; result: string }[],
    },
    cost: {
      eyebrow: "Sin rodeos",
      title: "Déjelo para después y no pasará nada. Ese es justo el problema.",
      text: "La pérdida nunca llega como una factura. Llega como tardes perdidas y un compañero que, sin ruido, se volvió más rápido que usted. Dos horas por semana son trece días laborables al año. El curso cuesta menos que uno de ellos.",
      cta: "Empezar esta semana",
    },
    faq: {
      eyebrow: "Preguntas",
      title: "Lo que más preguntan",
      items: [
        {
          q: "¿Y si no soy capaz?",
          a: "Una persona lee su trabajo: si no sale, le muestran exactamente dónde y le dan otra oportunidad. Y se empieza desde abajo del todo: si nunca ha usado IA, el primer nivel está escrito para usted.",
        },
        {
          q: "¿Quién lo enseña?",
          a: "Una profesora que ha trabajado con IBM, Amazon, OpenAI y Anthropic. Es la misma que lee y corrige sus tareas.",
        },
        {
          q: "Esto está gratis en YouTube.",
          a: "Lo está: a trozos, sin orden y sin nadie que le diga en qué se equivocó. Aquí paga el orden, las tareas sobre su propio trabajo y la revisión. Si tiene 200 horas libres, YouTube funciona de verdad.",
        },
        {
          q: "No soy nada técnico.",
          a: "Aquí no se programa en ningún momento. Si sabe usar un navegador, puede. Solo les cuesta a quienes no hacen las tareas.",
        },
        {
          q: "No tengo tiempo.",
          a: "Va a su ritmo y el acceso se queda con usted. Si de verdad no hay tiempo, empiece por el bonus de 49 minutos: da el cuadro completo en una tarde.",
        },
        {
          q: "¿Hace falta una suscripción de pago?",
          a: "Se puede empezar gratis. Donde un plan de pago ayuda, se lo decimos antes de que gaste nada.",
        },
        {
          q: "Ya uso ChatGPT todos los días.",
          a: "Entonces empiece por el nivel Intermediate. Los que vienen así suelen sacar más: llegan con trabajo real y ven cuánto siguen haciendo a mano.",
        },
        {
          q: "¿Qué pasa después de dejar mis datos?",
          a: "Le escribe una persona: cuándo puede empezar y cómo entrar. Sin embudos ni llamadas.",
        },
      ],
    },
    pricing: {
      eyebrow: "Precio",
      title: "Un curso. Un precio.",
      sub: "Sin planes ni extras. Todos reciben todo, revisión incluida.",
      was: "$299",
      now: "$150",
      includes: [
        "Seis partes: de la base a los agentes",
        "Tareas sobre su propio trabajo real",
        "Revisión y corrección por una profesora",
        "Bonus: 49 minutos para directivos",
        "El acceso y sus plantillas se quedan con usted",
      ],
      cta: "Dejar mis datos",
    },
    form: {
      title: "Dejar mis datos",
      sub: "Nombre y correo. Le responde una persona, normalmente el mismo día.",
      name: "Nombre",
      namePh: "Ana García",
      email: "Correo",
      emailPh: "tu@empresa.com",
      submit: "Enviar",
      sending: "Enviando…",
      success: "¡Gracias! Nos pondremos en contacto.",
      successSub: "Una persona le escribirá al correo y le contará qué sigue.",
      errName: "Indique su nombre.",
      errEmail: "Indique un correo válido.",
      errSend: "Algo salió mal. Inténtelo de nuevo.",
      privacy: "Usamos estos datos solo para contactarle. Sin newsletters.",
    },
    footer: {
      tagline: "Pide o perece.",
      rights: "Todos los derechos reservados.",
    },
  },

  ru: {
    label: "Русский",
    nav: {
      method: "Обучение",
      curriculum: "Программа",
      skills: "Навыки",
      pricing: "Цена",
      cta: "Получить доступ",
    },
    hero: {
      pill: "500+ выпускников · доступ остаётся навсегда",
      title: ["Научитесь поручать", "ИИ то, что вы до сих пор ", "делаете руками", "."],
      sub: "С нуля до собственных ИИ-помощников и автоматизаций. Урок, задание на вашей настоящей работе, проверка живым преподавателем. Без программирования, в вашем темпе.",
      cta: "Получить доступ",
      ghost: "Что внутри",
      was: "$299",
      now: "$150",
      save: "вы экономите $149",
      tags: ["ChatGPT", "Claude", "Gemini", "Без программирования"],
      gloss: "Prompta aut perire — с латыни «промпти или погибни». Промпт — это текст, которым вы объясняете нейросети, что вам нужно.",
      app: {
        heading: "заготовка 09",
        week: "урок 02",
        outLabel: "готовый ответ",
        result: [
          "Маржа выросла на 4% — за счёт двух крупных сделок",
          "Риск: один клиент даёт 40% выручки (с. 12)",
          "Решение: продлевать ли договор с подрядчиком",
        ],
        stack: ["заготовка 07", "заготовка 08"],
      },
    },
    field: {
      tasks: [
        "Недельный отчёт",
        "Письмо клиенту",
        "Договор проверен",
        "Сводка встречи",
        "Предложение готово",
        "Ответ на возражение",
        "Нужный пункт найден",
        "Описание товара",
        "Цена посчитана",
        "Счёт разобран",
        "Неделя расписана",
        "Тот же вопрос, ответ",
        "Документы сверены",
        "Тексты для сайта",
        "Источники разобраны",
        "Письмо после звонка",
      ],
    },
    authority: {
      eyebrow: "Кто учит",
      line: "Курс ведёт преподаватель, работавшая с IBM, Amazon, OpenAI и Anthropic.",
      items: ["IBM", "Amazon", "OpenAI", "Anthropic"],
      note: "Она же читает и правит ваши задания. Не теория из учебника, а практика изнутри компаний, которые всё это и делают.",
    },
    who: {
      eyebrow: "Для кого",
      title: "Работа у всех разная. Рутина — одинаковая.",
      sub: "Найдите здесь себя. Внутри курса вы делаете задания на своих задачах, а не на чужих.",
      items: [
        { role: "Руководители", task: "Недельный отчёт, разбор встреч, сводка, которую некому написать." },
        { role: "Продажи и работа с клиентами", task: "Предложение под конкретного клиента, ответ на возражение, письмо после звонка." },
        { role: "Финансы и юристы", task: "Проверить договор, сверить документы, найти нужный пункт в сотне страниц." },
        { role: "Врачи, преподаватели, исследователи", task: "Материалы, планы, разбор источников, ответы на одни и те же вопросы в десятый раз." },
        { role: "Предприниматели", task: "Описания товаров, тексты для сайта, расчёт цены, проверка идеи до того, как тратить деньги." },
        { role: "Кто работает один", task: "Всё перечисленное. Помощник, которого вы не можете себе нанять." },
      ],
    },
    pain: {
      eyebrow: "Знакомо?",
      title: "Вы знаете, что ИИ мог бы это сделать. И всё равно делаете сами.",
      items: [
        {
          q: "Смотрели видео про ИИ, а в пустом чате не знаете, что написать.",
          a: "Видео показывают кнопки. Никто не показывает, как довести вашу задачу до готового результата.",
        },
        {
          q: "Ответ приходит гладкий и не по делу. Переписываете сами.",
          a: "Дело не в ИИ, а в том, как вы просите. Этому учатся за пару часов.",
        },
        {
          q: "Каждый понедельник — тот же отчёт, та же сводка.",
          a: "Это можно отдать один раз и больше никогда не делать руками.",
        },
        {
          q: "Коллега успевает за час то, на что у вас уходит день.",
          a: "Он не умнее. У него есть заготовки. Свои вы соберёте здесь.",
        },
      ],
    },
    mechanism: {
      eyebrow: "В чём разница",
      title: "Вы собираете заготовки. По одной за урок.",
      lede: "Приёмы забываются. Заготовка — нет. Один раз описали задачу, дальше просто запускаете: каждый понедельник, для каждого клиента.",
      pillars: [
        {
          n: "Делаете",
          title: "Заготовку под вашу задачу",
          text: "Ваш настоящий отчёт, ваше письмо, ваш договор. Не учебный пример.",
        },
        {
          n: "Проверяют",
          title: "Преподаватель находит ошибки",
          text: "Читает то, что вы собрали, и показывает, где это подведёт. Видео так не умеет.",
        },
        {
          n: "Остаётся",
          title: "Заготовка ваша навсегда",
          text: "К концу у вас их набор. Работают, даже когда вы забыли, как их делали.",
        },
      ],
      example: {
        label: "Вот как она выглядит",
        name: "Еженедельный отчёт для директора",
        askLabel: "Это вы пишете один раз, обычными словами",
        lines: [
          "Ты готовишь отчёт для директора. Она читает 90 секунд.",
          "Я пришлю цифры за неделю. Дай: что изменилось и почему,",
          "один риск и одно решение, которое ждёт её.",
          "Одна страница, без прилагательных.",
        ],
        outLabel: "А это приходит в ответ каждый понедельник",
        out: [
          "Маржа: 18% → 22%. Две крупные сделки в октябре, с. 4.",
          "Отток клиентов: 3% → 7%. Задержки на складе в Казани, с. 9.",
          "Средний чек: $560 → $640, с. 6.",
          "Риск: один клиент даёт 40% выручки. Уйдёт — минус треть плана, с. 12.",
          "Ждёт вашего решения: продлевать ли договор с подрядчиком. До 30-го.",
        ],
        before: "Было: вечер вторника на сведение цифр и подбор формулировок.",
        after: "Стало: вставили цифры — отчёт готов за полминуты.",
        note: "Это всё. Обычный текст, написанный словами и сохранённый один раз. К концу курса таких заготовок у вас девять — под ваши повторяющиеся задачи.",
      },
      close: "Поэтому нашими заготовками пользуются и через полгода после курса.",
    },
    scene: {
      eyebrow: "Чему вы научитесь",
      title: "Каждый урок заканчивается тем, что работает.",
      note: "Листайте дальше и смотрите, как это складывается. Девять умений в шести частях — от того, как всё это вообще устроено, до агентов, которые делают работу без вас.",
      counter: "умений собрано",
    },
    demo: {
      eyebrow: "Посмотрите",
      title: "Вся разница — в том, как попросили",
      lede: "Та же нейросеть, та же задача. Слева и справа — обычный текст, который пишут словами прямо в чат. Выберите, что ближе вам.",
      badLabel: "Как пишет большинство",
      goodLabel: "Как напишете вы",
      resultLabel: "Ответ",
      note: "Никаких секретных слов. Просто понятное объяснение: кто читает, что важно, в каком виде нужен ответ.",
      tabs: [
        {
          id: "report",
          label: "Отчёт руководителю",
          bad: {
            prompt: "Сделай краткое содержание этого отчёта для директора.",
            result: [
              "Компания продолжает демонстрировать устойчивую динамику.",
              "Отдел продаж провёл ряд результативных встреч.",
              "Ситуация с поставщиками остаётся под контролем.",
              "Рекомендуется продолжить мониторинг ключевых показателей.",
            ],
            verdict: "Ни одной цифры. Переписываете сами — сорок минут.",
          },
          good: {
            prompt: [
              "Справка директору. Она читает 90 секунд и сначала спрашивает про деньги.",
              "Дай: три цифры, которые изменились, и почему.",
              "Два риска — со ссылкой на страницу.",
              "Одно решение, которое ждёт её.",
              "Одна страница.",
            ],
            result: [
              "Маржа: 18% → 22%. Две крупные сделки в октябре, с. 4.",
              "Отток клиентов: 3% → 7%. Задержки на складе в Казани, с. 9.",
              "Средний чек: $560 → $640, с. 6.",
              "Риск: один клиент даёт 40% выручки, с. 12.",
              "Ждёт вашего решения: продлевать ли договор с подрядчиком, до 30-го.",
            ],
            verdict: "Отправляете как есть. Полминуты.",
          },
        },
        {
          id: "client",
          label: "Плохая новость клиенту",
          bad: {
            prompt: "Напиши клиенту, что сроки сдвигаются на две недели.",
            result: [
              "Уважаемый Иван Иванович!",
              "К сожалению, вынуждены сообщить, что по независящим от нас",
              "обстоятельствам сроки реализации проекта сдвигаются.",
              "Приносим искренние извинения и надеемся на понимание.",
            ],
            verdict: "Ни даты, ни плана. Клиент звонит вашему руководителю.",
          },
          good: {
            prompt: [
              "Клиент ждал 14-го, будет 28-го. Причина: подвёл поставщик.",
              "Первая строка — новая дата и что клиент получит уже на этой неделе.",
              "Дальше причина одним предложением, без оправданий.",
              "В конце: что нужно от клиента и до какого числа.",
              "Восемь строк, спокойный тон.",
            ],
            result: [
              "Иван, новая дата сдачи — 28 октября.",
              "Макеты и тексты отдам в четверг, работать с ними можно уже сейчас.",
              "Причина: поставщик сорвал поставку, замену нашли за три дня.",
              "От вас нужно: утвердить макеты до 21-го.",
              "Если позже — 28-е тоже сдвинется, и я скажу об этом сразу.",
            ],
            verdict: "Клиент отвечает по делу, а не звонит начальству.",
          },
        },
        {
          id: "contract",
          label: "Проверить договор",
          bad: {
            prompt: "Прочитай договор и скажи, что в нём не так.",
            result: [
              "Договор в целом составлен стандартно.",
              "Обратите внимание на разделы об оплате и сроках.",
              "Некоторые формулировки могут быть уточнены.",
              "Рекомендуем проконсультироваться с юристом.",
            ],
            verdict: "Читаете договор сами. Вечер.",
          },
          good: {
            prompt: [
              "Я исполнитель. Бюджет $12 000, срок три месяца.",
              "Найди пункты, из-за которых я могу работать или платить сверх договора.",
              "Найди, где заказчик может расторгнуть без компенсации.",
              "По каждому: цитата, номер пункта и что предложить взамен.",
              "Нормальные пункты не упоминай.",
            ],
            result: [
              "п. 4.2 — «правки вносятся до полного удовлетворения Заказчика».",
              "→ Это работа без конца. Замена: «не более двух кругов правок».",
              "п. 7.1 — расторжение в любой момент без оплаты выполненного.",
              "→ Замена: «оплата фактически выполненного на дату расторжения».",
              "п. 9.3 — штраф 0,5% в день, верхней границы нет.",
              "→ Замена: «но не более 10% от суммы договора».",
            ],
            verdict: "Три ловушки с номерами и готовой заменой. Двадцать минут.",
          },
        },
      ],
    },
    method: {
      eyebrow: "Как проходит обучение",
      title: "Вас учат, а не выдают доступ",
      lede: "Обычные курсы дают папку с видео. Её не досматривают. Здесь следующий урок не откроется, пока не сделан предыдущий.",
      steps: [
        { n: "01", title: "Урок", text: "Короткий, по делу, вокруг одной задачи." },
        { n: "02", title: "Тест", text: "Не поняли — дальше не пустит." },
        { n: "03", title: "Задание", text: "На вашей настоящей работе, а не на выдуманном примере." },
        { n: "04", title: "Проверка", text: "Живой человек читает и правит то, что вы сделали." },
      ],
      ui: {
        brand: "Prompta · платформа обучения",
        week: "Трек 2 · Beginner",
        progress: "62%",
        moduleLabel: "Beginner · Как просить",
        lessons: [
          { state: "done", title: "Что модель может, а что нет", meta: "зачёт" },
          { state: "done", title: "Четыре части рабочего запроса", meta: "зачёт" },
          { state: "now", title: "Ваш еженедельный отчёт", meta: "на проверке" },
          { state: "lock", title: "Проверка идеи на выдуманных клиентах", meta: "откроется после проверки" },
        ],
        lessonTitle: "Урок 5 · Ваш еженедельный отчёт",
        yours: "Ваша заготовка",
        yourLines: [
          "Ты готовишь отчёт для директора. Она читает 90 секунд.",
          "Дай: что изменилось и почему, один риск и одно решение.",
        ],
        reviewBy: "Разбор · ваш преподаватель",
        review:
          "Структура хорошая. Две правки: укажите, откуда берутся цифры, иначе модель их придумает. И попросите риск со ссылкой на страницу. Пересдайте — и готово.",
        actions: ["Исправить и пересдать", "Сохранить в библиотеку"],
      },
      platform: "Всё происходит на нашей платформе: уроки, задания, проверки, прогресс. С компьютера и с телефона, в удобные вам часы.",
      note: "Если нужна просто папка с видео — вам не сюда. Здесь придётся работать.",
    },
    curriculum: {
      eyebrow: "Программа",
      title: "Шесть частей. От «я ничего не знаю» до собственных агентов.",
      sub: "Четыре трека по порядку, бонус для тех, у кого нет времени, и план на то, что будет дальше.",
      modules: [
        {
          n: "01",
          title: "База",
          text: "Что такое нейросеть на самом деле и что значат токены, галлюцинации, работа с вашими документами и агенты — человеческим языком, без формул.",
          result: "Знаете, чему верить, а что проверять.",
        },
        {
          n: "02",
          title: "Beginner",
          text: "ChatGPT и Claude уверенно: диалоги, файлы, картинки, голос — и что нельзя загружать в чат никогда.",
          result: "Работаете сами, не подглядывая, как это делается.",
        },
        {
          n: "03",
          title: "Intermediate",
          text: "Как просить правильно: от одного вопроса до многоразовых заготовок, своей библиотеки и помощников, которые знают вашу компанию.",
          result: "Ответ отправляете как есть.",
        },
        {
          n: "04",
          title: "Advanced",
          text: "Автоматизация и агенты: расписания, браузерные агенты, дашборды и калькуляторы без кода, несколько агентов в связке — и где здесь риски.",
          result: "Рутина идёт без вашего участия.",
        },
        {
          n: "05",
          title: "Бонус · 49 минут",
          text: "Сжатый разбор для руководителей, у которых нет времени: что решать, что делегировать, за чем следить.",
          result: "Вся картина за один вечер.",
        },
        {
          n: "06",
          title: "Что делать дальше",
          text: "Как перевести на это команду: где ИИ нельзя доверять, что мерить и как держать под контролем.",
          result: "Показываете эффект в цифрах.",
        },
      ],
    },
    outcomes: {
      eyebrow: "Навыки",
      title: "Девять вещей, которые вы будете уметь",
      sub: "Найдите свою — ту, из-за которой у вас регулярно горит вечер.",
      skills: [
        { title: "Отличать правду от выдумки", text: "ИИ уверенно придумывает цифры и источники. Вы поймаете это до того, как отправите документ." },
        { title: "Получать нужное с первого раза", text: "Тот же запрос, объяснённый правильно. Переписывать не придётся." },
        { title: "Разбирать документы", text: "Договор, отчёт, счёт, скан: что важно, где подвох, чего не хватает. Плюс глубокий поиск, который возвращается со ссылками." },
        { title: "Иметь помощника, который вас знает", text: "Знает вашу компанию, ваших клиентов и ваш стиль. Отвечает сразу по-вашему." },
        { title: "Работать голосом и экраном", text: "Надиктовали по дороге. Показали экран — объяснили задачу, не написав ни слова." },
        { title: "Снять с себя рутину", text: "Отчёты, сводки, разбор встреч идут по расписанию, без вашего участия." },
        { title: "Проверять идеи без риска", text: "Ваш текст или вашу цену сначала разносят выдуманные клиенты." },
        { title: "Собирать себе инструменты", text: "Дашборд, калькулятор, небольшая программа — за вечер, без единой строчки кода." },
        { title: "Перевести на это отдел", text: "Ставите то же самое команде и показываете результат в цифрах." },
      ],
      stats: [
        { v: "500+", l: "Выпускников" },
        { v: "6", l: "Частей" },
        { v: "100%", l: "Работ проверено" },
        { v: "0", l: "Строчек кода" },
      ],
    },
    testimonials: {
      eyebrow: "Выпускники",
      title: "Что говорят после курса",
      items: [] as { quote: string; name: string; role: string; result: string }[],
    },
    cost: {
      eyebrow: "Честно",
      title: "Отложите — ничего страшного не случится. В этом и проблема.",
      text: "Потеря не приходит счётом. Она приходит потерянными вечерами и коллегой, который тихо стал быстрее вас. Два часа в неделю — это тринадцать рабочих дней в год. Курс стоит меньше одного такого дня.",
      cta: "Начать на этой неделе",
    },
    faq: {
      eyebrow: "Вопросы",
      title: "О чём спрашивают чаще всего",
      items: [
        {
          q: "А если у меня не получится?",
          a: "Задания проверяет человек — если не выходит, вам покажут, где именно, и дадут переделать. И начинаете вы с самого низа: если вы никогда не пользовались ИИ, первый трек написан как раз для вас.",
        },
        {
          q: "Кто ведёт курс?",
          a: "Преподаватель, работавшая с IBM, Amazon, OpenAI и Anthropic. Она же читает и правит ваши задания.",
        },
        {
          q: "Это же есть бесплатно на YouTube.",
          a: "Есть — кусками, без порядка, и без человека, который скажет, что вы сделали не так. Вы платите за порядок, задания на своей работе и проверку. Если у вас есть 200 свободных часов — YouTube честно работает.",
        },
        {
          q: "Я совсем не технарь.",
          a: "Программирования здесь нет нигде. Умеете пользоваться браузером — справитесь. Тяжело только тем, кто не делает задания.",
        },
        {
          q: "У меня нет времени.",
          a: "Проходите в своём темпе, доступ остаётся у вас. Если времени совсем нет — начните с бонусных 49 минут: там вся картина за один вечер.",
        },
        {
          q: "Нужна платная подписка?",
          a: "Начать можно бесплатно. Где платная удобнее — скажем заранее, до того как вы что-то потратите.",
        },
        {
          q: "Я и так пользуюсь ChatGPT каждый день.",
          a: "Тогда начинайте с трека Intermediate. Такие обычно выносят больше всех: приходят с настоящими задачами и видят, сколько всё ещё делают руками.",
        },
        {
          q: "Что после заявки?",
          a: "Вам напишет человек: когда можно начать и как попасть на обучение. Без автоворонок и звонков.",
        },
      ],
    },
    pricing: {
      eyebrow: "Цена",
      title: "Одна программа. Одна цена.",
      sub: "Без тарифов и доплат. Все получают всё, включая проверку работ.",
      was: "$299",
      now: "$150",
      includes: [
        "Шесть частей: от базы до агентов",
        "Задания на ваших настоящих задачах",
        "Проверка и разбор живым преподавателем",
        "Бонус: 49 минут для руководителей",
        "Доступ и ваши заготовки остаются у вас",
      ],
      cta: "Оставить заявку",
    },
    form: {
      title: "Оставить заявку",
      sub: "Имя и почта. Вам ответит человек — обычно в тот же день.",
      name: "Имя",
      namePh: "Мария Иванова",
      email: "Почта",
      emailPh: "you@company.com",
      submit: "Отправить",
      sending: "Отправляем…",
      success: "Спасибо! Мы свяжемся с вами.",
      successSub: "Человек напишет вам на почту и расскажет, что дальше.",
      errName: "Укажите имя.",
      errEmail: "Укажите корректную почту.",
      errSend: "Что-то пошло не так. Попробуйте ещё раз.",
      privacy: "Данные нужны только чтобы связаться с вами. Никаких рассылок.",
    },
    footer: {
      tagline: "Промпти или погибни.",
      rights: "Все права защищены.",
    },
  },
};

export type Copy = (typeof content)["en"];
