// Downloads the web fonts into public/fonts and writes app/fonts.css, so the
// site serves its own typefaces instead of depending on Google being
// reachable from the visitor's country. Re-run after changing FAMILIES.
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const FAMILIES = [
  "Onest:wght@400;600;700;800",
  "Manrope:wght@400;500;600;700",
];

// Latin for the English and Spanish pages, Cyrillic for the Russian one.
const SUBSETS = ["latin", "latin-ext", "cyrillic", "cyrillic-ext"];

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const root = process.cwd();
const fontDir = join(root, "public/fonts");
mkdirSync(fontDir, { recursive: true });

const url =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map((f) => `family=${f}`).join("&") +
  "&display=swap";

const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

// Each @font-face is preceded by a /* subset */ comment.
const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[^}]*\})/g)];
const out = [
  "/* Self-hosted web fonts — generated by scripts/fetch-fonts.mjs.",
  "   Do not edit by hand; re-run the script instead. */",
  "",
];
let downloaded = 0;

for (const [, subset, face] of blocks) {
  if (!SUBSETS.includes(subset)) continue;

  const family = face.match(/font-family: '([^']+)'/)[1];
  const weight = face.match(/font-weight: (\d+)/)[1];
  const src = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)[1];
  const file = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${subset}.woff2`;
  const dest = join(fontDir, file);

  if (!existsSync(dest)) {
    const res = await fetch(src, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`${src} → ${res.status}`);
    writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
    downloaded++;
  }

  out.push(
    face
      .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${file}')`)
      .replace(/\n\s*font-display: swap;/, "\n  font-display: swap;"),
    "",
  );
}

writeFileSync(join(root, "app/fonts.css"), out.join("\n"));
console.log(`fonts: ${downloaded} downloaded, ${blocks.length} faces seen`);
